In [1]:
import torch
torch.__version__

'1.13.1+cu117'

### Basic Tensors: shape, dimension, data types

In [23]:
# scaler
scaler = torch.tensor(4)
scaler, scaler.shape, scaler.ndim, scaler.item() , scaler.dtype

(tensor(4), torch.Size([]), 0, 4, torch.int64)

In [3]:
# vector 
vec = torch.tensor([7,3])
vec, vec.shape, vec.ndim, # no vec.item() 

(tensor([7, 3]), torch.Size([2]), 1)

In [4]:
# Matrix
MAT = torch.tensor([[4,6,5]])
MAT, MAT.shape, MAT.ndim

(tensor([[4, 6, 5]]), torch.Size([1, 3]), 2)

In [5]:
# Tensor
TENSOR = torch.tensor([[[1, 2, 4],
                        [8, 3, 6],
                        [2, 9, 7]]])

TENSOR, TENSOR.shape, TENSOR.ndim

(tensor([[[1, 2, 4],
          [8, 3, 6],
          [2, 9, 7]]]),
 torch.Size([1, 3, 3]),
 3)

In [10]:
# random tensor 

v1 = torch.rand([2,5])
v1, v1.dtype, v1.ndim , v1.shape

(tensor([[0.4454, 0.2734, 0.8970, 0.0972, 0.9231],
         [0.0259, 0.7488, 0.2173, 0.7590, 0.9923]]),
 torch.float32,
 2,
 torch.Size([2, 5]))

In [13]:
torch.zeros([1,5]) , torch.ones([1,5])  

(tensor([[0., 0., 0., 0., 0.]]), tensor([[1., 1., 1., 1., 1.]]))

In [15]:
torch.zeros_like(v1) # similarly ones_like

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [21]:
torch.arange(5,15,2)

tensor([ 5,  7,  9, 11, 13])

In [33]:
torch.tensor([1.,8.], dtype = torch.float16) 

tensor([1., 8.], dtype=torch.float16)

In [39]:
### Basic operations
v1, v1 + 5

(tensor([[0.4454, 0.2734, 0.8970, 0.0972, 0.9231],
         [0.0259, 0.7488, 0.2173, 0.7590, 0.9923]]),
 tensor([[5.4454, 5.2734, 5.8970, 5.0972, 5.9231],
         [5.0259, 5.7488, 5.2173, 5.7590, 5.9923]]))

In [40]:
v1*5

tensor([[2.2272, 1.3668, 4.4851, 0.4858, 4.6153],
        [0.1295, 3.7442, 1.0866, 3.7950, 4.9617]])

### Matrix Multiplication

In [52]:
t1 = torch.rand([3,2])
t2 = torch.rand([3,2])

t1@t2.T , torch.matmul(t1,t2.T), torch.mm(t1, t2.T)

(tensor([[0.5003, 0.8525, 0.4364],
         [0.4679, 0.7766, 0.3869],
         [0.5438, 0.9989, 0.5488]]),
 tensor([[0.5003, 0.8525, 0.4364],
         [0.4679, 0.7766, 0.3869],
         [0.5438, 0.9989, 0.5488]]),
 tensor([[0.5003, 0.8525, 0.4364],
         [0.4679, 0.7766, 0.3869],
         [0.5438, 0.9989, 0.5488]]))

### Min, max

In [76]:
t1 = torch.arange(5,15,2)
t1.min(), t1.max()

(tensor(5), tensor(13))

In [78]:
t2 = torch.tensor([[1,5,6], [12,0,6]])
t2.min() , t2.argmin()

(tensor(0), tensor(4))

In [100]:
a = torch.randn(3, 2)
print(a)
torch.argmin(a), torch.argmin(a, dim=1) , torch.argmin(a, dim=1, keepdim=True)

tensor([[-0.6096, -0.4601],
        [ 1.5846, -0.2892],
        [-0.7289,  1.5529]])


(tensor(4),
 tensor([0, 1, 0]),
 tensor([[0],
         [1],
         [0]]))

### Change dtype 


In [104]:
# Create a float16 tensor
tensor_float16 = t1.type(torch.float16)
tensor_float16

tensor([ 5.,  7.,  9., 11., 13.], dtype=torch.float16)

### reshape, permute, squeeze

In [114]:
t1 = torch.arange(8)
t1, t1.reshape([2,4])

(tensor([0, 1, 2, 3, 4, 5, 6, 7]),
 tensor([[0, 1, 2, 3],
         [4, 5, 6, 7]]))

In [128]:
t1_view = t1.view([2,4]) # same memory used 
t1_view

tensor([[0, 1, 2, 3],
        [4, 5, 6, 7]])

In [129]:
t1_view[1,2] = 100

In [131]:
t1_view, t1

(tensor([[  0,   1,   2,   3],
         [  4,   5, 100,   7]]),
 tensor([  0,   1,   2,   3,   4,   5, 100,   7]))

In [134]:
t1.unsqueeze(0),t1.unsqueeze(1)

(tensor([[  0,   1,   2,   3,   4,   5, 100,   7]]),
 tensor([[  0],
         [  1],
         [  2],
         [  3],
         [  4],
         [  5],
         [100],
         [  7]]))

In [137]:
t2 = torch.rand([1,1,2,3])
t2, t2.shape, t2.ndim

(tensor([[[[0.2747, 0.1120, 0.7107],
           [0.2758, 0.1027, 0.8623]]]]),
 torch.Size([1, 1, 2, 3]),
 4)

In [139]:
t2.squeeze(), t2.squeeze().shape

(tensor([[0.2747, 0.1120, 0.7107],
         [0.2758, 0.1027, 0.8623]]),
 torch.Size([2, 3]))

### Permute

In [144]:
t3 = t2.squeeze()
t3.shape

torch.Size([2, 3])

In [148]:
t3

tensor([[0.2747, 0.1120, 0.7107],
        [0.2758, 0.1027, 0.8623]])

In [146]:
t3.permute([1,0])

tensor([[0.2747, 0.2758],
        [0.1120, 0.1027],
        [0.7107, 0.8623]])

### Indexing and Slicing 

In [157]:
t3[0,1] , t3[1,2], t3[:, 1]

(tensor(0.1120), tensor(0.8623), tensor([0.1120, 0.1027]))

### Numpy and torch

In [167]:
import numpy as np
torch.from_numpy(np.array([2,6,5,74,]))

tensor([ 2,  6,  5, 74], dtype=torch.int32)

In [168]:
torch.from_numpy(np.array([2,6,5,74,])).type(torch.float)

tensor([ 2.,  6.,  5., 74.])

In [173]:
t3.numpy()

array([[0.27469796, 0.11197537, 0.7107383 ],
       [0.2757731 , 0.10265452, 0.8622501 ]], dtype=float32)

### Random seed and cuda

In [189]:
torch.manual_seed(42)

torch.rand([1,2])  # rerun it we get the same tensor

tensor([[0.8823, 0.9150]])

In [193]:
t1.device

device(type='cpu')

In [196]:
t2 = t1.to('cuda')
t2

tensor([  0,   1,   2,   3,   4,   5, 100,   7], device='cuda:0')

In [197]:
t2.cpu()

tensor([  0,   1,   2,   3,   4,   5, 100,   7])

In [198]:
t2.to('cpu')

tensor([  0,   1,   2,   3,   4,   5, 100,   7])